fix(schema): add missing `settings` type
The JSON schema is missing a type for the `settings` key.

To reproduce this, create a `mise.toml` with a `[settings]` key and lint
the file using the JSON schema.

```sh
printf '[settings]\n' >mise.toml
uvx --from "tombi>=0.5,<0.6" tombi lint --no-cache mise.toml
```

```log
Error: invalid json pointer: #/$defs/settings,
schema_uri: https://mise.jdx.dev/schema/mise.json
```

This commit will add `"type": "object"` to the `settings` key in the
JSON schema.

Signed-off-by: Brendon Smith <bws@bws.bio>