fix: complete task arguments correctly (#8601)
This fixes a bug where triggering a completion in the task args would
cause an error, especially with flags in zsh:

```sh
$ mise tasks run build -- -c <COMPLETE>
Error:   × unexpected word: -c
```

This is particularly noticeable when using shell aliases because passing
flags to commands is much more command than to tasks:

```sh
$ my_build -c <COMPLETE>
Error:   × unexpected word: -c
```

The bug is caused by mounting the `mise tasks --usage`. It contains
command definitions for each task. They take precedence over the
ARGS_LAST definition.

The bug is fixed (unelegantly) by adding the ARGS_LAST to every command
in `mise tasks --usage`. There is likely a better fix for this in the
`usage` project but we're also using both `arg "[TASK]"` and `cmd`,
which already seems to be a conflict in principle.