fix: Xonsh integration (#5557)
The Xonsh integration is currently broken. It doesn't output any errors
when running `execx($(mise activate -s xonsh))`, but calling `mise`
after doing so will raise an error:

```
joe@vingilot ~/Documents/code/mise main @ execx($(mise activate xonsh))
joe@vingilot ~/Documents/code/mise main @ mise
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
Exception in thread {'cls': 'ProcProxyThread', 'name': 'Thread-33', 'func': FuncAlias({'name': 'mise', 'func': '_mise', 'return_what': 'result'}), 'alias': 'mise', 'pid': None}
FileNotFoundError: [Errno 2] No such file or directory: 'command'
```

Ultimately this error is due to the activating script trying to execute
`command mise ...`, and `command` isn't a proper executable. `command`
is a Bash builtin (and maybe exists in other more bash-like shells as
well?), so I'm guessing what happened was that some logic was ported
over from other shells and doesn't work here.

Fixing this issue is straightforward, but doing so reveals a second
issue. The pre-prompt hook attempts to capture the output of `mise
hook-env` via `$(...)`, but this doesn't work because `mise` has been
replaced with an alias that runs it using `subprocess.run()`, which
bypasses Xonsh's output-capturing mechanics.

To fix these issues I suggest the following changes:
* Use normal `xonsh` subprocess semantics in the main `mise` alias,
which fixes output capturing
* Since the original motivation for using `subprocess.run()` was to
speed up execution, but we really only care about this in the pre-prompt
hook, we will use `subprocess.run()` only in the pre-prompt hook.
* Switch to passing in the Xonsh environment via `XSH.env.detype()`.
This avoids the added complexity of having to set env vars in both
`XSH.env` and `os.environ`, which significantly cleans up the
implementation.
* Add an `e2e` test for Xonsh, at least for the basic behavior. I
modeled this one mostly after the e2e test for Zsh.

If that seems reasonable, I have a couple of additional questions:
1. There's [a section in the
docs](https://mise.jdx.dev/dev-tools/shims.html#hook-on-cd) that talks
about hooking into `cd`, rather than just running every time the prompt
is displayed. This makes sense to me - the PATH manipulation that mise
does should only need to be updated when the working directory changes -
but I'm not sure if it means what I think it means. At least, the docs
claim that this happens in Bash and Zsh, but looking at those
implementations it appears that they are still running on prompt as well
as on `cd`, so I'm not sure what's going on. If my original intuition is
right and the hook only really needs to fire when the directory is
changed, this would be easy to do in Xonsh as well. We'd just need to
hook into the `on_chdir` event instead of `on_pre_prompt`.
2. `shfmt` doesn't like the Xonsh test script, which is understandable
since Xonsh syntax can get pretty far from regular shell (all valid
Python is also valid Xonsh.) Unfortunately it's causing some checks to
fail in CI, and I can't find a way to tell it to ignore this file, or
just mark it as an expected fail. Is that possible?