fix: Fix syntax error on `activate nu` when PATH contains shims (#4349)
## Background and Purpose

When nushell has shims in the PATH, `activate nu` outputs an incorrect
script.

The problem is at the beginning of the script generated by `activate nu`
```
set,Path,C:\Program Files\Microsoft VS Code\bin;C:\Program Files\PowerShell\7
```

This gives the following error in nushell 0.102.
```
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #55:1:1]
 1 │ set,Path,C:\Program Files\Microsoft VS Code\bin;C:\Program Files\PowerShell\7
   · ─────────┬─────────
   ·          ╰── Command `set,Path,C:\Program` not found
   ╰────
  help: `set,Path,C:\Program` is neither a Nushell built-in or a known external command
```

This is not a Nu script, but a CSV protocol.
The nushell functions defined in `activate` (`def “parse vars”`) parse
CSV only for `deactivate`, `shell` and `sh` command output.
The CSV protocol is not available in `activate` itself, so it must
output valid Nu scripts.

## Changes
- `Shell::set_env` should change the output if it is running in the
context of `activate`. I introduced `enum ActivatePrelude` to avoid
making it mutable.

## Impact
- The output of other shells is kept the same.

Co-authored-by: jdx <216188+jdx@users.noreply.github.com>