Update nushell.rs - Add explicit spread
Running mise with nushell in the latest release of nushell (currently [0.89.0](https://www.nushell.sh/blog/2024-01-09-nushell_0_89_0.html#spread-operator-for-commands)) results in the following warning:

```shell
Error:   × Automatically spreading lists is deprecated
    ╭─[/hREDACTED:35:1]
 35 │   } else {
 36 │     ^"rtx" $command $rest
    ·                     ──┬──
    ·                       ╰── Spreading lists automatically when calling external commands is deprecated and will be removed in 0.91.
 37 │   }
    ╰────
  help: Use the spread operator (put a '...' before the argument)
```

This change fixes the warning.