fix: update flake.lock and add fix for rust-bindgen to default.nix (#8874)
This updates the flake.lock file as it was installing Rust 1.85 and
several crates no longer support that version:

```shell
❯ nix develop
❯ mise run build
[build] $ cargo build --all-features
error: rustc 1.85.0 is not supported by the following packages:
  aws-config@1.8.12 requires rustc 1.88
  aws-credential-types@1.2.11 requires rustc 1.88
  aws-runtime@1.5.18 requires rustc 1.88
  aws-sdk-s3@1.121.0 requires rustc 1.88.0
...
```

This PR also adds `bindgenHook` to `default.nix` so that `bindgen` can
work (see
https://ryantm.github.io/nixpkgs/languages-frameworks/rust/#hooks):

```shell
❯ nix develop
❯ mise run build
[build] $ cargo build --all-features
 ...
error: failed to run custom build command for `aws-lc-sys v0.39.0`
...
  thread 'main' (116706) panicked at /var/home/esteve/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.72.1/lib.rs:616:27:
  Unable to find libclang: "the `libclang` shared library at /usr/lib64/llvm21/lib64/libclang.so.21.1.8 could not be opened: libLLVM.so.21.1: cannot open shared object file: No such file or directory"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
[build] ERROR task failed
```

---------

Signed-off-by: Esteve Fernandez <esteve@apache.org>
Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>
Co-authored-by: jdx <216188+jdx@users.noreply.github.com>