fix: broken build by declaring cmake as a tool
Without cmake installed `cargo build` will yield an error message like:

```
warning: aws-lc-sys@0.32.3: NASM command not found or failed to execute.
warning: aws-lc-sys@0.32.3: NASM command not found or failed to execute.
error: failed to run custom build command for `aws-lc-sys v0.32.3`

Caused by:
  process didn't exit successfully: `C:\projects\mise\target\debug\build\aws-lc-sys-2a357fba9d5c77b2\build-script-main` (exit code: 101)
  ...
  --- stderr
  Missing dependency: cmake

  thread 'main' panicked at C:\Users\nick\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\aws-lc-sys-0.32.3\builder\main.rs:463:40:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So this commit adds it.