fix: NoMethodError with Bundler::Installer (#5678)
Sorry, I introduced new issue with https://github.com/jdx/mise/pull/5676

```
NoMethodError: undefined method 'reshim' for an instance of Bundler::Installer
```

This PR fixed that. Thanks!