Fix concat for nushell script (#3591)
Since https://github.com/nushell/nushell/pull/14344 (4d3283e),
the `++` (concat) operator does not support appending a bare value
to a list.

The current nushell script will result in this error in latest nushell:

```
Error: nu::shell::type_mismatch

  × Type mismatch during operation.
    ╭─[mise.nu:14:47]
 13 │   let old_hooks = $old_config | get $field --ignore-errors | default []
 14 │   $env.config = ($old_config | upsert $field ($old_hooks ++ $new_hook))
    ·                                               ─────┬──── ─┬ ────┬────
    ·                                                    │      │     ╰── record<condition: closure, code: closure>
    ·                                                    │      ╰── type mismatch for operator
    ·                                                    ╰── list<closure>
 15 │ }
    ╰────
```

So here we can fix it, in a backwards compatible manner,
by wrapping the `$new_hook` value in brackets
to form a list containing the single item.